import api from './axios'

export const getProjects = () => api.get('/projects')
export const getProjectById = (id) => api.get(`/projects/${id}`)
export const createProject = (payload) => api.post('/projects', payload)
export const updateProject = (id, payload) => api.put(`/projects/${id}`, payload)
export const patchProject = (id, payload) => api.patch(`/projects/${id}`, payload)
export const deleteProject = (id) => api.delete(`/projects/${id}`)
export const getProjectSummary = (id) => api.get(`/projects/${id}/summary`)
export const addProjectPhase = (id, payload) => api.post(`/projects/${id}/phases`, payload)
export const getPhaseCost = (id) => api.get(`/phases/${id}/cost`)
export const addPhaseMaterial = (phaseId, payload) => api.post(`/phases/${phaseId}/materials`, payload)
export const addPhaseLabor = (phaseId, payload) => api.post(`/phases/${phaseId}/labor`, payload)
export const addPhaseEquipment = (phaseId, payload) => api.post(`/phases/${phaseId}/equipment`, payload)
export const deleteProjectPhase = (phaseId) => api.delete(`/phases/${phaseId}`)
export const deletePhaseMaterial = (phaseId, itemId) => api.delete(`/phases/${phaseId}/materials/${itemId}`)
export const deletePhaseLabor = (phaseId, itemId) => api.delete(`/phases/${phaseId}/labor/${itemId}`)
export const deletePhaseEquipment = (phaseId, itemId) => api.delete(`/phases/${phaseId}/equipment/${itemId}`)
export const patchPhase = (phaseId, payload) => api.patch(`/phases/${phaseId}`, payload)
